version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 80:80
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 3000:3000
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: