version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 80:5984
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 3001:3001
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: